Fix broken brew audit in debian image
Linuxbrew/docker pull request #14
Opened 2017-07-19 21:50 UTC by VonUniGE

On a fresh Linuxbrew debian image running `brew audit` on a formula gives:
```
linuxbrew@9e93cefe5a31:~$ brew audit htop
==> Installing or updating 'rubocop' gem
Fetching: rainbow-2.2.2.gem (100%)
Building native extensions.  This could take a while...
ERROR:  Error installing rubocop:
	ERROR: Failed to build gem native extension.

    current directory: /home/linuxbrew/.gem/ruby/2.3.0/gems/rainbow-2.2.2/ext
/usr/bin/ruby2.3 mkrf_conf.rb

current directory: /home/linuxbrew/.gem/ruby/2.3.0/gems/rainbow-2.2.2/ext
/usr/bin/ruby2.3 -rubygems /usr/share/rubygems-integration/all/gems/rake-10.5.0/bin/rake RUBYARCHDIR=/home/linuxbrew/.gem/ruby/2.3.0/extensions/x86_64-linux/2.3.0/rainbow-2.2.2 RUBYLIBDIR=/home/linuxbrew/.gem/ruby/2.3.0/extensions/x86_64-linux/2.3.0/rainbow-2.2.2
/usr/bin/ruby2.3: No such file or directory -- /usr/share/rubygems-integration/all/gems/rake-10.5.0/bin/rake (LoadError)

rake failed, exit code 1

Gem files will remain installed in /home/linuxbrew/.gem/ruby/2.3.0/gems/rainbow-2.2.2 for inspection.
Results logged to /home/linuxbrew/.gem/ruby/2.3.0/extensions/x86_64-linux/2.3.0/rainbow-2.2.2/gem_make.out
Error: Failed to install/update the 'rubocop' gem.
```

After installing the linuxbrew ruby version, the error disappear. I propose to add 
```
RUN brew install ruby
```
in the Dockerfile.

P.S.: 
* Linuxbrew Ruby version = 2.4.1p111 
* Debian Stretch Ruby version = 2.3.3p222

2017-07-22 08:48 UTC, sjackman requested changes
Thanks for the pull request, @VonUniGE.

I believe the current image has no Linuxbrew formula installed, and I'd prefer to keep it that way, to provide a completely empty Linuxbrew installation. Two options…
1. Install the Debian packages needed so that `brew audit` works.
2. Do not install the Debian Ruby package and instead use the Linuxbrew `portable-ruby` package. It should be installed by default if no `ruby` executable is found.

2017-07-24 13:15 UTC, VonUniGE commented
Option 1) is not a solution since the current ruby package installed from debian is version 2.3.3 and it's already the newest available one. The same version (2.3.3) is available in debian stretch (stable), buster (testing) and sid (unstable).

I've choosed option 2, and remove the ruby package installed by debian and the ruby package installed by Linuxbrew. I run one time `brew list` at the end of the Dockerfile to install `portable-ruby`. (I tried to run only `brew` but it returns an error code that make the `make` process fail.)

2017-07-24 13:32 UTC, sjackman requested changes
One small change. Otherwise, looks good to me.

2017-07-24 13:32 UTC, sjackman commented on debian/Dockerfile
> +RUN brew list
Can you please change `brew list` to `brew doctor`?

2017-07-24 15:59 UTC, rwhogg commented on debian/Dockerfile
> +# Install portable-ruby by running brew a first time
[Nitpick] Can you please change "a" to "for the"?

2017-07-24 16:00 UTC, bw-yuhogg requested changes
Left one nitpick, after fixing that and Shaun's previous suggestion, IMO it's good to me.

Thanks again @VonUniGE :)

2017-07-24 16:03 UTC, rwhogg commented
Can you apply the same change to the Ubuntu Dockerfile too? It has the same problem.

2017-07-24 22:23 UTC, VonUniGE commented on debian/Dockerfile
> +RUN brew list
Ok, it's commited.

2017-07-24 22:23 UTC, VonUniGE commented on debian/Dockerfile
> +# Install portable-ruby by running brew a first time
Sure, it's committed now.

2017-07-24 22:26 UTC, bw-yuhogg approved these changes

2017-07-25 02:46 UTC, merged

2017-07-25 02:46 UTC, rwhogg commented
Merged. Thanks again @VonUniGE!