README.md: minor improvements
Linuxbrew/docker pull request #47
Opened 2019-01-01 10:06 UTC by maxim-belkin

Mostly stylistic changes. Feel free to reject.

2019-01-02 01:28 UTC, sjackman requested changes
One change, otherwise looks good. Thanks, Maxim!

2019-01-02 01:28 UTC, sjackman commented on README.md
> +Linuxbrew Dockerfiles for various distributions of Linux.
I prefer the previous wording for this line.

2019-02-11 06:30 UTC, maxim-belkin commented on README.md
> +Linuxbrew Dockerfiles for various distributions of Linux.
Previous wording is not accurate, is it? `...for using Linuxbrew on various distributions of Linux` conveys the idea that these Dockerfiles allow one to use Linuxbrew on various Linux distributions. These files, however, allow one to use Linuxbrew on any OS with Docker installed.
`Linuxbrew Dockerfiles for various distributions of Linux.` is not super accurate either...

2019-02-11 06:51 UTC, sjackman commented on README.md
> +Linuxbrew Dockerfiles for various distributions of Linux.
How about…
```suggestion
Dockerfiles for installing Linuxbrew on various distributions of Linux.
```
To me the purpose of the Dockerfile is to install Linuxbrew on an a distribution of Linux inside Docker. It's understood that Docker is running on some other arbitrary distribution of Linux.

2019-02-12 17:29 UTC, maxim-belkin commented on README.md
> +Linuxbrew Dockerfiles for various distributions of Linux.
Let me, actually, undo this change. I don't agree with "on various distributions of Linux." so it'll be easier to just not touch it in this PR.

2019-02-12 17:36 UTC, merged