alpine: use install script from Homebrew
Linuxbrew/docker pull request #72
Opened 2020-04-18 07:54 UTC by VonUniGE

Use the install script
```
https://raw.githubusercontent.com/Homebrew/install/master/install.sh
```
instead of
```
https://raw.githubusercontent.com/Linuxbrew/install/master/install
```
The Homebrew install script needs the coreutils and the grep alpine packages. Alpine use by default busybox commands and some needed options are missing in these commands.

A symbolic link from `/usr/bin/touch` touch to `/bin/touch` has been created and the Alpine version has been set to 3.11

The Apache Tomcat server have been successfully installed and run with Homebrew.

2020-04-20 19:36 UTC, sjackman requested changes
Thank you for this fix, @VonUniGE !

2020-04-20 19:36 UTC, sjackman commented on alpine/Dockerfile
> -
Please leave this blank line.

2020-04-20 19:36 UTC, sjackman commented on alpine/Dockerfile
> -
Ditto.

2020-04-20 19:36 UTC, sjackman commented on alpine/Dockerfile
> -
Ditto.

2020-04-20 20:22 UTC, VonUniGE commented
Blank lines added.

2020-04-21 16:42 UTC, merged

2020-04-21 16:43 UTC, sjackman commented
Merged. Thanks again, @VonUniGE !