fedora: use install script from Homebrew
Linuxbrew/docker pull request #76
Opened 2020-04-24 21:49 UTC by VonUniGE

Use the install script
```
https://raw.githubusercontent.com/Homebrew/install/master/install.sh
```
instead of
```
https://raw.githubusercontent.com/Linuxbrew/install/master/install
```
- The fedora base image has been upgraded to fedora:31 (latest)
- The gcc package have been added to the image to avoid the following scenario:
```
[linuxbrew@8c7d4df6f7e3 ~]$ brew install gcc
==> Installing dependencies for gcc: patchelf, gmp, mpfr, libmpc, zlib, binutils and isl@0.18
==> Installing gcc dependency: patchelf
==> Downloading https://linuxbrew.bintray.com/bottles/patchelf-0.10.x86_64_linux.bottle.tar.gz
Already downloaded: /home/linuxbrew/.cache/Homebrew/downloads/405227c46362964d2bc2e9ff6428fe082dff4dbd3a4b0b29453743f71923304b--patchelf-0.10.x86_64_linux.bottle.tar.gz
==> Pouring patchelf-0.10.x86_64_linux.bottle.tar.gz
Error: patchelf must be installed: brew install patchelf
Warning: Bottle installation failed: building from source.
Error: The following formula
  patchelf
cannot be installed as binary package and must be built from source.
Install Clang or run `brew install gcc`.
```

2020-04-24 22:11 UTC, sjackman commented
```
==> Installing gcc dependency: patchelf
==> Downloading https://linuxbrew.bintray.com/bottles/patchelf-0.10.x86_64_linux.bottle.tar.gz
Already downloaded: /home/linuxbrew/.cache/Homebrew/downloads/405227c46362964d2bc2e9ff6428fe082dff4dbd3a4b0b29453743f71923304b--patchelf-0.10.x86_64_linux.bottle.tar.gz
==> Pouring patchelf-0.10.x86_64_linux.bottle.tar.gz
Error: patchelf must be installed: brew install patchelf
Warning: Bottle installation failed: building from source.
```
That's a bug in Homebrew/brew. Could you please open an issue against Homebrew/brew and tag me?

2020-04-24 22:12 UTC, sjackman requested changes

2020-04-24 22:12 UTC, sjackman commented on fedora/Dockerfile
> +RUN dnf install -y curl file gcc git glibc-locale-source make ruby rubygem-json rubygem-test-unit sudo which \
Please revert this change.

2020-04-24 22:30 UTC, VonUniGE commented on fedora/Dockerfile
> +RUN dnf install -y curl file gcc git glibc-locale-source make ruby rubygem-json rubygem-test-unit sudo which \
Ok, done.

2020-04-25 10:17 UTC, VonUniGE commented
I think the problem doesn't come from the Homebrew install script but from a circular dependency between `gcc` and `patchelf`:

```
linuxbrew@8c9c5a9564f4:~/.linuxbrew/Cellar$ brew install -v gcc
==> Installing dependencies for gcc: patchelf, gmp, mpfr, libmpc, zlib, binutils and isl@0.18
==> Installing gcc dependency: patchelf
==> Downloading https://linuxbrew.bintray.com/bottles/patchelf-0.10.x86_64_linux.bottle.tar.gz
Already downloaded: /home/linuxbrew/.cache/Homebrew/downloads/405227c46362964d2bc2e9ff6428fe082dff4dbd3a4b0b29453743f71923304b--patchelf-0.10.x86_64_linux.bottle.tar.gz
==> Verifying 405227c46362964d2bc2e9ff6428fe082dff4dbd3a4b0b29453743f71923304b--patchelf-0.10.x86_64_linux.bottle.tar.gz checksum
==> Pouring patchelf-0.10.x86_64_linux.bottle.tar.gz
tar xof /home/linuxbrew/.cache/Homebrew/downloads/405227c46362964d2bc2e9ff6428fe082dff4dbd3a4b0b29453743f71923304b--patchelf-0.10.x86_64_linux.bottle.tar.gz -C /tmp/d20200425-8745-1mdenmy
cp -pR /tmp/d20200425-8745-1mdenmy/patchelf/. /home/linuxbrew/.linuxbrew/Cellar/patchelf
chmod -Rf +w /tmp/d20200425-8745-1mdenmy
Error: patchelf must be installed: brew install patchelf
Warning: Bottle installation failed: building from source.
Error: The following formula
  patchelf
cannot be installed as binary package and must be built from source.
Install Clang or run `brew install gcc`.
```


```
linuxbrew@8c9c5a9564f4:~$ brew install -v patchelf
==> Downloading https://linuxbrew.bintray.com/bottles/patchelf-0.10.x86_64_linux.bottle.tar.gz
Already downloaded: /home/linuxbrew/.cache/Homebrew/downloads/405227c46362964d2bc2e9ff6428fe082dff4dbd3a4b0b29453743f71923304b--patchelf-0.10.x86_64_linux.bottle.tar.gz
==> Verifying 405227c46362964d2bc2e9ff6428fe082dff4dbd3a4b0b29453743f71923304b--patchelf-0.10.x86_64_linux.bottle.tar.gz checksum
==> Pouring patchelf-0.10.x86_64_linux.bottle.tar.gz
tar xof /home/linuxbrew/.cache/Homebrew/downloads/405227c46362964d2bc2e9ff6428fe082dff4dbd3a4b0b29453743f71923304b--patchelf-0.10.x86_64_linux.bottle.tar.gz -C /tmp/d20200425-7974-139ceaw
cp -pR /tmp/d20200425-7974-139ceaw/patchelf/. /home/linuxbrew/.linuxbrew/Cellar/patchelf
chmod -Rf +w /tmp/d20200425-7974-139ceaw
Error: patchelf must be installed: brew install patchelf
Warning: Bottle installation failed: building from source.
Error: The following formula
  patchelf
cannot be installed as binary package and must be built from source.
Install Clang or run `brew install gcc`.
```
@sjackman Do you know why the `patchelf` bottle cannot be installed ?

2020-04-25 16:32 UTC, merged

2020-04-25 16:34 UTC, sjackman commented
Installing the `patchelf` bottle shouldn't require `patchelf`. That dependency is in Homebrew/brew.

2020-04-25 16:34 UTC, sjackman commented
Merged. Thanks again, @VonUniGE !